src/main/java/edu/wpi/grip/core/operations/PythonScriptOperation.java, src/test/java/edu/wpi/grip/core/PythonTest.java
One property needs to be set for Jython to work.  This used to be set in
the python unit test, but to actually use python in the application, we
might as well just set it in a static block in PythonScriptOperation
=> Initialize Python properties in PythonScriptOperation

src/main/java/edu/wpi/grip/core/Socket.java, src/main/java/edu/wpi/grip/core/events/ConnectionAddedEvent.java, src/main/java/edu/wpi/grip/core/events/ConnectionRemovedEvent.java, src/main/java/edu/wpi/grip/core/events/SocketConnectedChangedEvent.java, src/main/java/edu/wpi/grip/ui/PipelineView.java, src/main/java/edu/wpi/grip/ui/SocketControlView.java, src/main/java/edu/wpi/grip/ui/SocketHandleView.java, src/main/resources/edu/wpi/grip/ui/GRIP.css, src/main/resources/edu/wpi/grip/ui/SocketControl.fxml
The basic work for adding and removing connections between steps is done.  You can add a new connection by clicking and dragging one socket to another.  You can remove connections by clicking either of the associated sockets.
Still todo:
* Ensure that only one connection is associated with a single input socket at any time
* Ensure that the user doesn't make "backwards" connections (these can cause infinite feedback loops and freeze the program if the values never converge)
* ~~Re-position `ConnectionView`s when the socket handles move around~~
* Maybe show a fancy animated `ConnectionView` while the user is dragging
=> Add and remove connections

src/main/java/edu/wpi/grip/ui/SocketControlView.java
Sockets with a view hint of `SocketHint.View.SELECT` should show a
drop-down menu (aka ChoiceBox) allowing the user to select from a
discrete list of possible inputs.  This is most useful for operations
that accept an enumeration as one of their inputs.
=> Add a ChoiceBox option for socket controls

src/main/java/edu/wpi/grip/ui/controllers/MainWindowController.java
Now that we can add and remove steps and connections from the user
interface, there's no need to showcase those controls with throwaway
code.
=> Get rid of the automatic demo pipeline manipulation

src/main/java/edu/wpi/grip/core/Socket.java, src/main/java/edu/wpi/grip/core/SocketHint.java, src/main/java/edu/wpi/grip/core/operations/PythonScriptOperation.java, src/main/java/edu/wpi/grip/core/operations/opencv/AddOperation.java, src/main/java/edu/wpi/grip/core/serialization/PythonScriptOperationConverter.java, src/main/java/edu/wpi/grip/core/sources/ImageFileSource.java, src/main/java/edu/wpi/grip/ui/controllers/MainWindowController.java, src/test/java/edu/wpi/grip/core/AdditionOperation.java, src/test/java/edu/wpi/grip/core/ConnectionTest.java, src/test/java/edu/wpi/grip/core/PythonTest.java, src/test/java/edu/wpi/grip/core/SinkTest.java, src/test/java/edu/wpi/grip/core/SocketTest.java, src/test/java/edu/wpi/grip/core/serialization/SerializationTest.java, src/test/java/edu/wpi/grip/core/sources/ImageFileSourceTest.java, src/test/resources/edu/wpi/grip/scripts/addition-subtraction.py, src/test/resources/edu/wpi/grip/scripts/addition-with-name-and-description.py, src/test/resources/edu/wpi/grip/scripts/addition-wrong-output-count.py, src/test/resources/edu/wpi/grip/scripts/addition-wrong-output-type.py, src/test/resources/edu/wpi/grip/scripts/addition.py
Instead of specifying a default value for sockets where no other value
is set, you can specify a function that returns an initial value for any
socket that isn't initialized with a value.  This ensures that all
sockets have a value, and also that those values can each be a new
instance (for mutable types like Mat).
For example, to make every socket have 5 as an initial value:
sh = new SocketHint<>("my-socket", Integer.class, 5);
But to make every socket construct a new Mat as an initial value (so
they don't all share the same instance):
sh = new SocketHint<>("my-socket", Mat.class, Mat::new);
When constructing the sockets themselves, it's not necessary to specify a
default value, but that constructor is still there in case you want to
immediately set a value other than the initial one …
=> Add SocketHint default values with Suppliers

src/main/java/edu/wpi/grip/core/Connection.java, src/main/java/edu/wpi/grip/core/Socket.java, src/main/java/edu/wpi/grip/core/Step.java, src/main/java/edu/wpi/grip/core/sources/ImageFileSource.java, src/test/java/edu/wpi/grip/core/ConnectionTest.java, src/test/java/edu/wpi/grip/core/StepTest.java
This can be used by the GUI to validate some user input, and also to
make it easier and cleaner to add specific things to the input and
output JavaFX controls (like options to preview outputs)
Basically, `Step` (as well as any other class that creates sockets) is
responsible for setting a direction on the socket after creating it.  By not
putting it in SocketHint, we avoid a ton of redundant boilerplate code in
every single operation and python script, and we also don't break
our existing code.
=> Add a getDirection() method to sockets to distinguish inputs/outputs

src/main/java/edu/wpi/grip/core/OutputSocket.java, src/main/java/edu/wpi/grip/core/Socket.java, src/main/java/edu/wpi/grip/core/Step.java
In Socket::setValue(), it doesn't really make sense to not send a
SocketChangedEvent if the new value is equal to the old value, since
some types (like Mat) can actually be modified in-place.
Since the "optimization" of not sending events doesn't really come up in
practice anywhere intentional, it's better just to remove this check.
For this to not break everything, we have to make sure that steps only
update if one of their inputs changes, not if *any* of their sockets
changes.  It should probably be like this anyways, because otherwise
we're running twice as many operations as we need to.
=> Don't try to be clever about not sending SocketChangedEvents

src/main/java/edu/wpi/grip/ui/preview/ImageSocketPreviewView.java, src/main/java/edu/wpi/grip/ui/preview/SocketPreviewView.java, src/main/java/edu/wpi/grip/ui/preview/SocketPreviewViewFactory.java, src/main/java/edu/wpi/grip/ui/preview/TextAreaSocketPreviewView.java
This fixes several issues with socket previews that came up when
integrating opencv functions
- They should only take `OutputSocket`s
- They should not rely on JavaFX properties to know when sockets change
- Image previews should not attempt to render empty images (we might
want to make a placeholder image eventually)
=> Fix previews to work with opencv functions

src/main/java/edu/wpi/grip/ui/pipeline/ConnectionView.java
Connections are rendered as a cubic curve.  This change adjusts the
positions of the control points so they are influenced by the positions
of both sockets.  Blender's node editor seems to use the same algorithm.
=> Make the connection curves slightly nicer

src/main/java/edu/wpi/grip/core/OutputSocket.java, src/main/java/edu/wpi/grip/core/SocketHint.java, src/main/java/edu/wpi/grip/ui/controllers/MainWindowController.java, src/main/java/edu/wpi/grip/ui/pipeline/OutputSocketView.java, src/test/java/edu/wpi/grip/core/SinkTest.java, src/test/java/edu/wpi/grip/core/SocketTest.java
This adds a "publishable" field to SocketHint that controls if a socket
can be set to be published to a sink.  It doesn't make sense for a lot
of sockets to be able to be published
Not preventing it would create confusion (mats would likely be published
somewhere as the result of Mat::toString(), which is almost certainly
not was the user things).  Plus, the publish buttons create visual
clutter.
Since the default setting is `false`, we should make sure that anything
that could be published is set as publishable.  This probably means
manually tagging certain opencv output parameters as publishable.
=> Only make sockets publishable if their socket hint says so

src/main/java/edu/wpi/grip/core/sources/ImageFileSource.java, src/main/java/edu/wpi/grip/ui/pipeline/AddSourceView.java, src/test/java/edu/wpi/grip/core/PipelineTest.java, src/test/java/edu/wpi/grip/core/sources/ImageFileSourceTest.java
Instead of using a java URL object, ImageFileSource should just take a
File and convert it to the right path format using the Paths class.
I tested this on a Windows machine, and it works.
=> Fix paths for ImageFileSource to be OS-independant

src/main/java/edu/wpi/grip/ui/preview/SocketPreviewView.java
If you have a bunch of previews called "dst", it's helpful to be able to
tell what they are the output of.
=> Show operation names in previews

src/main/resources/edu/wpi/grip/ui/GRIP.css
The "tallest" step we currently have (sobel) now fits within the bottom
half of my screen without scrolling.
=> Decrease the spacing between sockets

src/main/java/edu/wpi/grip/ui/preview/ImageSocketPreviewView.java
This is probably the cause of the mysterious scenegraph
NullPointerException that came up before.  The scenegraph should only be
manipulated from the UI thread, and the preview code is actually running
in the thread that eventBus.post was called in, which is the webcam
executor thread.  When multiple threads are touchin the scenegraph
probably hundreds of times per second, a race condition occasionally
happens.
We'll probably need some stress testing to make sure it's actually
fixed.
=> Update image previews in the UI thread

buildSrc/src/main/java/edu/wpi/gripgenerator/templates/SocketHintDeclarationCollection.java
Mats set as InputOutput param types now use `assignTo` instead of `setTo`
=> Fixes generated peform InputOutput param sockets

src/main/java/edu/wpi/grip/core/Socket.java, src/main/java/edu/wpi/grip/core/Step.java, src/main/java/edu/wpi/grip/ui/preview/SocketPreviewView.java
Since Sockets wont have steps for Sources this makes sense to prevent it from
being null.
=> Makes the Step in Socket an Optional value

buildSrc/src/main/java/edu/wpi/gripgenerator/FileParser.java, buildSrc/src/main/java/edu/wpi/gripgenerator/settings/DefinedMethod.java, buildSrc/src/main/java/edu/wpi/gripgenerator/settings/DefinedMethodCollection.java, buildSrc/src/main/java/edu/wpi/gripgenerator/settings/DefinedParamType.java, buildSrc/src/main/java/edu/wpi/gripgenerator/templates/SocketHintDeclaration.java, buildSrc/src/main/java/edu/wpi/gripgenerator/templates/SocketHintDeclarationCollection.java
Before the `setOutput` would force the state of the param. Now it only
sets it if it hasn't been set by the constructor.
Related #71
=> Fixes the DefinedParamState passed to constructor not taking priority

src/main/java/edu/wpi/grip/ui/pipeline/input/RangeInputSocketView.java, src/main/java/edu/wpi/grip/ui/pipeline/input/SliderInputSocketView.java, src/main/resources/edu/wpi/grip/ui/GRIP.css
Sliders now have tick marks and labels, and they don't have unnecessarily
large padding on the right.
=> Improve the appearance of sliders

src/main/java/edu/wpi/grip/Main.java, src/main/java/edu/wpi/grip/ui/OperationView.java, src/main/java/edu/wpi/grip/ui/pipeline/AddSourceView.java, src/main/java/edu/wpi/grip/ui/pipeline/ConnectionView.java, src/main/java/edu/wpi/grip/ui/pipeline/OutputSocketView.java, src/main/java/edu/wpi/grip/ui/pipeline/StepView.java, src/main/java/edu/wpi/grip/ui/preview/BlobsSocketPreviewView.java, src/main/java/edu/wpi/grip/ui/preview/LinesSocketPreviewView.java, src/main/java/edu/wpi/grip/ui/util/DPIUtility.java, src/main/resources/edu/wpi/grip/ui/GRIP.css, src/main/resources/edu/wpi/grip/ui/pipeline/OutputSocket.fxml
This change adds a "DPIUtility" class and migrates all dpi-specific
sizing to use it.  This should make the sizing a little more consistant
accross platforms and screen resolutions without including a bunch of
hacky hard-coded scales everywhere we use an image.
=> Fix cross-platform DPI scaling issues

buildSrc/src/main/groovy/edu/wpi/gripgenerator/CodeGenerator.groovy, buildSrc/src/main/java/edu/wpi/gripgenerator/FileParser.java
- Remove debug printlns that have been in there since the beginning
- Remove operations that don't do anything useful for us (ie: raw matrix operations that can't really be used in the pipeline)
- Remove mask parameters (this is broken now, we will discuss a way to do this right later)
=> Remove broken/not yet useful stuff from the generator

src/main/java/edu/wpi/grip/ui/MainWindowView.java, src/main/java/edu/wpi/grip/ui/PaletteView.java, src/main/java/edu/wpi/grip/ui/pipeline/ConnectionView.java, src/main/resources/edu/wpi/grip/ui/GRIP.css, src/main/resources/edu/wpi/grip/ui/Palette.fxml, src/main/resources/edu/wpi/grip/ui/pipeline/Pipeline.fxml, src/main/resources/edu/wpi/grip/ui/preview/Previews.fxml
This fixes some small issues with the GUI that have been bugging me:
- There's too much padding in a lot of places.
- The operations in the palette use a weird custom gradient and shadow
effect.
- Steps resize themselves to all be the same height, regardless of their
contents.
- The pipeline does not fill all the way to the bottom of the screen,
leaving a blank space where the border between the sources
and the steps disappears.
- The operation palette gets bigger when to make the window wider,
taking up more of the preview pane's space.
- "Focus" glowing effects show up on the preview pane and
palette if you click them.
**Before**:
**After**:
=> Small GUI enhancements

src/main/java/edu/wpi/grip/ui/OperationView.java, src/main/java/edu/wpi/grip/ui/pipeline/OutputSocketView.java, src/main/java/edu/wpi/grip/ui/pipeline/StepView.java, src/main/resources/edu/wpi/grip/ui/Operation.fxml, src/main/resources/edu/wpi/grip/ui/pipeline/OutputSocket.fxml, src/main/resources/edu/wpi/grip/ui/pipeline/Step.fxml
There were a few places where things such as constant widths and heights and mouse handlers were defined in Java.  Defining them declaratively in the FXML "view" instead of the Java "controller" is probably better MVC practice, and it also makes the controller code less cluttered.
=> Move UI layout settings from Java code to FXML where possible

.gitignore, build.gradle
Adds the ability to run ```gradlew idea``` and ```gradlew eclipse``` to setup a development environments with all dependencies linked and ready-to-go.
=> Add IDE plugins to buildscript

build.gradle, src/main/java/edu/wpi/grip/ui/PaletteView.java, src/main/java/edu/wpi/grip/ui/util/SearchUtility.java, src/main/resources/edu/wpi/grip/ui/Palette.fxml
Searching is now "fuzzy" - it will ignore differences in whitespace,
capitalization, and small typos.  It also takes into account both the
name of an operation and its description.
The visual glitch where the bottom of a filtered operation list gets get
off if the last operation's text overflows has been fixed (we just
needed to set the ScrollPane to always grow vertically)
Typing while the palette is focused will automatically focus the search
box.
closes #113
=> Improve operation searching

build.gradle, src/main/java/edu/wpi/grip/core/Main.java, src/main/java/edu/wpi/grip/ui/Main.java, src/test/java/edu/wpi/grip/ui/MainWindowTest.java
You can now run `./gradlew shadowJar` to generate a runnable headless
jar.  Currently, the main method for this jar does nothing.
=> Add a headless build

build.gradle
Prevents the JavaCPP OpenCV presets being fetched for all platforms, fetching only what is required for the User's machine.
=> Make Dependencies Platform-Dependent

src/main/java/edu/wpi/grip/ui/MainWindowView.java
From brad's email:
> And, the File Save operation is putting up a File Open dialog box on my mac so there’s no place to put the file name.
=> Show a "save" dialog instead of an "open" dialog when saving

build.gradle, src/main/java/edu/wpi/grip/core/sources/CameraSource.java
OpenCV's frame grabber framework seems to only work reliably for us on linux and osx, leading to crashes when using webcams on Windows.
Before this is merged, I'd like to get some testing done on a couple different computers and webcams.
closes #142
=> Use videoInput for webcam capture on Windows

core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java, ui/src/main/java/edu/wpi/grip/ui/preview/PointSizeSocketPreviewView.java
=> Fix adding empty string

ui/src/main/java/edu/wpi/grip/ui/pipeline/AddSourceView.java, ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineView.java
Our code is not really written to handle asyncronous GUI updates in many
situations, such as updating the pipeline view when steps are
added/deleted/moved.  So, in these situations we should block the
calling thread until the GUI thread has finished performing the
specified action.
In addition, it is not necessary to call Platorm.runLater() from the GUI
thread.
=> Fix Platform.runLater() usage

build.gradle
This brings the size of the headless jar down almost 30%, which should both make the distribution smaller (and probably more likely to be downloaded by people), and make the deploy time quicker.
On my system (Linux x86_64), the core jar is now 34.3 MB instead of 48 MB.
=> Exclude unused stuff from the jar

ui/src/main/java/edu/wpi/grip/ui/pipeline/input/RangeInputSocketView.java
Previously, the GUI messed up newly loaded sliders so the upper bound
was the default value
Closes #223
=> Correctly load range values

build.gradle
This will inflate the jar a small ammount and
slow down throwing of errors but will allow us
to get stack traces where we normally would have
lost them.
Thanks to this post:
https://plumbr.eu/blog/java/on-a-quest-for-missing-stacktraces
Related #225
=> Prevents JIT from eating stack traces

build.gradle, core/src/main/java/edu/wpi/grip/core/Main.java, ui/src/main/java/edu/wpi/grip/ui/DeployerController.java, ui/src/main/java/edu/wpi/grip/ui/GRIPUIModule.java, ui/src/main/java/edu/wpi/grip/ui/MainWindowController.java, ui/src/main/java/edu/wpi/grip/ui/deployment/DeploymentOptionsController.java, ui/src/main/java/edu/wpi/grip/ui/deployment/DeploymentOptionsControllersFactory.java, ui/src/main/java/edu/wpi/grip/ui/deployment/FRCAdvancedDeployment.java, ui/src/main/java/edu/wpi/grip/ui/deployment/FRCAdvancedDeploymentOptionsController.java, ui/src/main/java/edu/wpi/grip/ui/deployment/FRCDeploymentOptionsController.java, ui/src/main/java/edu/wpi/grip/ui/pipeline/AddSourceView.java, ui/src/main/java/edu/wpi/grip/ui/util/SupplierWithIO.java, ui/src/main/java/edu/wpi/grip/ui/util/deployment/DeployedInstanceManager.java, ui/src/main/java/edu/wpi/grip/ui/util/deployment/DeploymentCommands.java, ui/src/main/java/edu/wpi/grip/ui/util/deployment/SecureShellDetails.java, ui/src/main/resources/edu/wpi/grip/ui/DeployerPane.fxml, ui/src/main/resources/edu/wpi/grip/ui/MainWindow.fxml, ui/src/main/resources/edu/wpi/grip/ui/deployment/DeploymentOptions.fxml, ui/src/test/java/edu/wpi/grip/ui/util/deployment/DeployedInstanceManagerTest.java, ui/src/test/resources/edu/wpi/grip/ui/util/deployment/LoadThreeStepsTestSave.grip
Adds the ability to deploy and run GRIP on a remote platform.
There is currently no GUI for it at the moment
=> Feat: Remote Deployment and Running

ui/src/main/java/edu/wpi/grip/ui/preview/BlobsSocketPreviewView.java, ui/src/main/java/edu/wpi/grip/ui/preview/ContoursSocketPreviewView.java, ui/src/main/java/edu/wpi/grip/ui/preview/ImageSocketPreviewView.java, ui/src/main/java/edu/wpi/grip/ui/preview/LinesSocketPreviewView.java, ui/src/main/java/edu/wpi/grip/ui/util/ImageConverter.java, ui/src/test/java/edu/wpi/grip/ui/util/ImageConverterTest.java
If an image changed dimention in the preview pane
it's UI counterpart could be changed in the wrong thread.
This could cause random ArrayOutOfBounds Exceptions without
any context as to what was causing the problem.
This forces the ImageConverter.convert method to be run in the
UI thread or it will throw an exception.
Possibly related: #225
=> Fixes ImageConverter running in the wrong thread

core/src/main/java/edu/wpi/grip/core/GRIPCoreModule.java, core/src/main/java/edu/wpi/grip/core/StartStoppable.java, core/src/main/java/edu/wpi/grip/core/Step.java, core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java, core/src/main/java/edu/wpi/grip/core/util/ExceptionWitness.java, ui/src/main/java/edu/wpi/grip/ui/Main.java, ui/src/main/java/edu/wpi/grip/ui/components/StartStoppableButton.java, ui/src/main/java/edu/wpi/grip/ui/util/GRIPPlatform.java, ui/src/test/java/edu/wpi/grip/ui/util/GRIPPlatformTest.java
Before we treated InterruptedExceptions just like every other
type of exception. This is bad because it means that the thread
that had been asked to exit was having to go through the process
of displaying a UI component which was causing deadlocks.
Closes #236
=> Fixes Handling of InterruptedExceptions

build.gradle, core/src/main/java/edu/wpi/grip/core/Main.java, ui/src/main/java/edu/wpi/grip/ui/DeployerController.java, ui/src/main/java/edu/wpi/grip/ui/GRIPUIModule.java, ui/src/main/java/edu/wpi/grip/ui/MainWindowController.java, ui/src/main/java/edu/wpi/grip/ui/deployment/DeploymentOptionsController.java, ui/src/main/java/edu/wpi/grip/ui/deployment/DeploymentOptionsControllersFactory.java, ui/src/main/java/edu/wpi/grip/ui/deployment/FRCAdvancedDeploymentOptionsController.java, ui/src/main/java/edu/wpi/grip/ui/deployment/FRCDeploymentOptionsController.java, ui/src/main/java/edu/wpi/grip/ui/pipeline/AddSourceView.java, ui/src/main/java/edu/wpi/grip/ui/util/SupplierWithIO.java, ui/src/main/java/edu/wpi/grip/ui/util/deployment/DeployedInstanceManager.java, ui/src/main/java/edu/wpi/grip/ui/util/deployment/DeploymentCommands.java, ui/src/main/java/edu/wpi/grip/ui/util/deployment/SecureShellDetails.java, ui/src/main/resources/edu/wpi/grip/ui/DeployerPane.fxml, ui/src/main/resources/edu/wpi/grip/ui/MainWindow.fxml, ui/src/main/resources/edu/wpi/grip/ui/deployment/DeploymentOptions.fxml, ui/src/test/java/edu/wpi/grip/ui/util/deployment/DeployedInstanceManagerTest.java, ui/src/test/resources/edu/wpi/grip/ui/util/deployment/LoadThreeStepsTestSave.grip
Reverts WPIRoboticsProjects/GRIP#235
=> Revert "Revert "Feat: Remote Deployment and Running""

build.gradle, core/src/main/java/edu/wpi/grip/core/GRIPCoreModule.java, core/src/main/java/edu/wpi/grip/core/Main.java, ui/src/main/java/edu/wpi/grip/ui/DeployerController.java, ui/src/main/java/edu/wpi/grip/ui/Main.java, ui/src/main/java/edu/wpi/grip/ui/util/deployment/DeployedInstanceManager.java
- ARM Java does not support aop so we need to change what guice we are using
- Deploying can throw null pointers because writing text to the text box was
not in the UI thread.
- Logging was setup after the guice injector was loaded meaning problems with
injecting wouldn't be logged.
- The GRIPCore module assumed that the main file would be registered on the
event bus to log exceptions but it isn't until after the injector is created.
- The thread that manages starting GRIP on a remote device does not actually 
post a startstopped event if the shell crashes
=> Fix various deployment problems

core/src/main/java/edu/wpi/grip/core/NoSocketTypeLabel.java, core/src/main/java/edu/wpi/grip/core/SocketHint.java, core/src/main/java/edu/wpi/grip/core/operations/composite/BlobsReport.java, core/src/main/java/edu/wpi/grip/core/operations/composite/ContoursReport.java, core/src/main/java/edu/wpi/grip/core/operations/composite/LinesReport.java, ui/src/main/java/edu/wpi/grip/ui/pipeline/OutputSocketController.java, ui/src/main/java/edu/wpi/grip/ui/pipeline/input/InputSocketController.java
Instead of just using the raw class name, the GUI now calls this method
to the label for the type of a socket.  This lets us override the class
name in different ways in the core, fixing some layout issues with
really long labels.
=> Add getTypeLabel() method to SocketHint

.travis-scripts/push-javadoc-to-gh-pages.sh, .travis.yml, README.md, appveyor.yml
- Makes it so `:ui:assemble` only happens on deploy
- Appveyor now completes in ~ 8 min instead of 12
- Travis now completes in ~ 4 min instead of ~ 6 min
- Moves JavaDoc generation to only happen on merge with master
=> Speeds UP CI Builds

core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java, core/src/main/java/edu/wpi/grip/core/sources/IPCameraFrameGrabber.java, core/src/test/java/edu/wpi/grip/core/sources/CameraSourceTest.java
- The camera source could enter states where the the camera had crashed but
didn't properly stop itself and indicate this to the UI.
Closes #135
Related https://github.com/bytedeco/javacv/issues/299
=> Fixes various problems CameraSource

core/src/main/java/edu/wpi/grip/core/operations/networktables/NTPublishOperation.java
NetworkTables initializes itself automatically as soon as we create a table, which we do basically as soon as GRIP starts up.  This is kind of annoying because it creates a lot of noise in the logs when we're not actually using NetworkTables.
We can simply undo this by immediately calling `NetworkTables::shutdown()`, and it will only start back up again if we explicitly set the project settings to use NetworkTables.
=> Don't automatically start up NetworkTables

core/src/main/java/edu/wpi/grip/core/operations/networktables/NTPublishOperation.java
Reverts WPIRoboticsProjects/GRIP#311
This is an invalid fix.
This should not be merged this way.
I don't care if it bothered you. You do not get to make the executive decision on how this is fixed..
=> Revert "Don't automatically start up NetworkTables"

core/src/main/java/edu/wpi/grip/core/operations/composite/HSLThresholdOperation.java, core/src/main/java/edu/wpi/grip/core/operations/composite/HSVThresholdOperation.java, core/src/main/java/edu/wpi/grip/core/operations/composite/RGBThresholdOperation.java
inRange segfaults if we give it three channels of ranges but a single
channel image.  Throwing an IllegalArgumentException is not ideal, but
it's better than segfaulting.
Closes #178
Related #250
=> Check for number of channels in threshold operations

ui/src/main/java/edu/wpi/grip/ui/deployment/FRCDeploymentOptionsController.java, ui/src/main/java/edu/wpi/grip/ui/pipeline/input/NumberSpinnerInputSocketController.java, ui/src/main/java/edu/wpi/grip/ui/util/Spinners.java
Previously, in an attempt to prevent users from inputting invalid characters into spinners, the user experience of editing a number was severely diminished, and apparently some exceptions happened occasionally anyways.
WIth this change, users should be able to manipulate the spinner editor freely, with invalid characters properly filtered.  Entering no text results in the value not being committed.  AFAIK this should never cause a parsing/formatting exception
Closes #324
Closes #320
=> Fix the buggy spinner validation

core/src/main/java/edu/wpi/grip/core/events/UnexpectedThrowableEvent.java, core/src/main/java/edu/wpi/grip/core/util/SafeShutdown.java, ui/src/main/java/edu/wpi/grip/ui/Main.java
This was caused because a shtdown hook threw an exception.
Our main application is designed to try to handle threads dying by
displaying a UI element. This should not be done in a shutdown hook.
What we have to do is ensure that when we try dto display the
exception alert it isn't from inside a shutdown hook.
Closes #297
=> Fix windows hanging when being shutdown

ui/src/main/java/edu/wpi/grip/ui/ExceptionAlert.java, ui/src/main/resources/edu/wpi/grip/ui/GRIP.css
GitHub's servers (and many modern browsers) apparently don't like us redirecting users to thousand-character-long URLs to automatically fill in issue forms.  So, I got rid of that whole thing and just put the generated text in the exception alert.  Users can copy and paste it themselves.
The list of system properties was also updated to remove some redundant/useless ones.  We can always ask for more info if necessary, but the ones removed can all be derived from existing ones.  This should just clear up some visual clutter.
The lack of styling in the alert has also bothered me for a while, so that's fixed now.
Closes #330
=> Exception alert enhancements

ui/src/main/java/edu/wpi/grip/ui/deployment/FRCAdvancedDeploymentOptionsController.java
Changed FRCAdvancedDeploymentOptionsController->postInit() so that the deploy button for the 'FRC Advanced' section of the 'FRC Deploy' dialog is enabled by default.
This closes issue #343.
=> Deploy button for the 'FRC Advanced' section of the 'FRC Deploy' dialog is enabled by default.

ui/src/main/java/edu/wpi/grip/ui/pipeline/OutputSocketController.java
The preview button would initialize off regardless
of how the save file had the preview state set.
Closes #253
=> Fixes OutputSockets preview button toggled wrong

core/src/main/java/edu/wpi/grip/core/operations/composite/DesaturateOperation.java
This was caused by not copying the input to the output
and just simply assigning the value of the input to the
output.
Closes #252
I actually had a comment on that line when this code was introduced but the comment was never resolved.
https://github.com/WPIRoboticsProjects/GRIP/pull/63/files#r43678331
Any way this can be prevented in the future?
=> Fixes Desaturate Feeding back into the previous step

core/src/main/java/edu/wpi/grip/core/GRIPCoreModule.java
The problem was we were setting up the logger multiple times
durring the test's lifecycle.
We should only have one global logger setup durring the tests.
Closes #309
=> Fixes tests creating multiple log files in home directory

core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java, core/src/test/java/edu/wpi/grip/core/sources/CameraSourceTest.java
This fixes an issue where the onStopPipeline event
would throw an exception if the camera source was
already stopped.
Closes #353
=> Fixes stopped camera exception stop pipeline event

core/src/main/java/edu/wpi/grip/core/operations/composite/PublishVideoOperation.java
`javax.imageio` is not supported on the embedded JRE on the roboRIO. Also, since we can convert Mats directly instead of converting them into AWT images, this is probably faster and uses less memory.
=> Use OpenCV instead of javax.imageio to encode M-JPEG stream

core/src/main/java/edu/wpi/grip/core/operations/composite/ContoursReport.java, core/src/main/java/edu/wpi/grip/core/operations/composite/FilterContoursOperation.java
This lets you filter contours by their "solidity", which is the ratio of their area to the area of their convex hull. 
You can technically filter out false positives by just having a minimum area, but that means that actual targets will be filtered out if you're too far away from them.  In addition, larger false positives will still show up.
The FIRST Stronghold targets have a solidity of about 1/3 regardless of how far away they are, so using a solidity filter gets them very reliably.
=> Add solidity filter

ui/src/main/java/edu/wpi/grip/ui/preview/PreviewsController.java
Instead of manually inserting them, which is verbose and error prone, we
can use JavaFX's built-in sorting routines to make the preview order
match up with the order of the things in the pipeline being previewed
This be merged in before we do the release, since the old code causes crashes
Closes #398
=> Use FXCollections.sort to sort preview views

build.gradle
We **cannot** use `git describe` to generate versions, since you can't
just use any arbitrary string as the version with JavaFX's packaging
tools.  .deb and .rpm builds both fail if you do this on a commit that
isn't tagged, or is tagged in a way other than v1.1.0 (for example,
release candidates)
=> v1.1.0 for real

build.gradle
This PR renames the JavaFX Installer Artifacts be appended with the system architecture. On Windows x64, this results in the following:
**Original Artifact Name**: GRIP-1.1.1.exe
**New Artifact Name**: GRIP-1.1.1-x64.exe
This closes issue #415
=> Have JavaFX Installer Artifacts be appended with the system architecture

ui/src/main/java/edu/wpi/grip/ui/DeployController.java
This was causing problems when the full path of the local GRIP jar has spaces in it.
Closes #435
=> Fix lack of URL decoding when deploying

build.gradle
This PR will close #428 upon merging
=> Fix OS 32-bit artifact fetching

build.gradle
=> Add AutoVersioning to gradle

core/src/main/java/edu/wpi/grip/core/settings/ProjectSettings.java, ui/src/main/java/edu/wpi/grip/ui/DeployController.java, ui/src/main/java/edu/wpi/grip/ui/MainWindowController.java, ui/src/main/java/edu/wpi/grip/ui/util/StringInMemoryFile.java, ui/src/main/resources/edu/wpi/grip/ui/Deploy.fxml, ui/src/main/resources/edu/wpi/grip/ui/GRIP.css
JVM arguments can be specified, and some reasonable defaults are included for new projects (and old projects created before this change).  These settings should help reduce OOM errors, and help us debug new ones.
Running from a robot program is now also easier, since a new wrapper script is included to facilitate the JVM options.
```c++
void RobotInit() override {
system("/home/lvuser/grip &");
}
```
In addition, the resulting file name of the deployed project can be changed from the default of "project.grip".  This lets you upload multiple versions to the roboRIO, and then the robot code can select one of them at the start of a match, although the robot code to run the project might be a little more complicated in this case.
We also now check the MD5 sum of the JAR before deploying it. …
=> Add JVM args and more options to the deploy dialog

ui/src/main/java/edu/wpi/grip/ui/DeployController.java
As long as GRIP is always launched from the wrapper, this should prevent
problems (such as OOM errors) from multiple instances of GRIP running
=> Automatically kill existing instances of GRIP from the  wrapper

core/src/main/java/edu/wpi/grip/core/operations/composite/BlobsReport.java, core/src/main/java/edu/wpi/grip/core/operations/composite/ContoursReport.java, core/src/main/java/edu/wpi/grip/core/operations/composite/LinesReport.java, core/src/main/java/edu/wpi/grip/core/operations/networktables/NTNumber.java, core/src/main/java/edu/wpi/grip/core/operations/networktables/NTPublishOperation.java, core/src/main/java/edu/wpi/grip/core/operations/networktables/NTValue.java, core/src/main/java/edu/wpi/grip/core/operations/networktables/NTVector2D.java, core/src/test/java/edu/wpi/grip/core/operations/networktables/NTPublishOperationTest.java
This fixes two problems:
- Publishable fields now much have a "weight".  This determines the
order that the checkboxes are in, preventing issues with different JVM
versions returning methods in different orders.
- If a publishable value has no (sub) key, it's put directly in the key
for the entire step.  This was sort of the behavior before, but
previously NetworkTables automatically put a trailing slash at the
end.  OutlineViewer still shows it the same, but robot programs did
not work unless they included this trailing slash.
Closes #432
=> Fix NTPublishOperation problems

core/src/main/java/edu/wpi/grip/core/serialization/Project.java, core/src/test/java/edu/wpi/grip/core/serialization/ProjectTest.java
When opening projects with missing settings, we should use the default
values for those settings.  By default, XStream sets them to null, but
we can override that using `PureJavaReflectionProvider`.
Closes #491
=> Fix deserializing ProjectSettings from previous GRIP versions

core/src/main/java/edu/wpi/grip/core/Main.java, ui/src/main/java/edu/wpi/grip/ui/Main.java
In GUI mode, a file name can be specified to open, and --headless can be
added to the command to make it not really open the GUI.
In headless mode, we don't really need to listen for hangup signals
(since the wrapper script will kill any old instances of GRIP), so we
can remove that to make it work on non-unix systems.
Closes #493
Closes #492
=> Add command line parsing in GUI mode and headless Windows support

core/src/main/java/edu/wpi/grip/core/GRIPCoreModule.java, core/src/main/java/edu/wpi/grip/core/Pipeline.java, core/src/main/java/edu/wpi/grip/core/operations/networktables/NTManager.java, core/src/main/java/edu/wpi/grip/core/util/GRIPMode.java, ui/src/main/java/edu/wpi/grip/ui/GRIPUIModule.java, ui/src/main/java/edu/wpi/grip/ui/Main.java, ui/src/test/java/edu/wpi/grip/ui/pipeline/PipelineUITest.java, ui/src/test/java/edu/wpi/grip/ui/pipeline/input/InputSocketControllerFactoryTest.java
This lets robot programs start and stop GRIP to save CPU without having
to wait for the process to start up again.
For example,
```java
NetworkTable table = NetworkTable.getTable("GRIP");
table.putBoolean("run", false); // Stop GRIP without killing the process
doSomeStuffThatDoesntNeedVision();
table.putBoolean("run", true); // Start GRIP again
```
This should be useful for teams that want to do auto alignment in teleop, since they could start and stop vision processing whenever the driver presses the button to auto aim.
Closes #501
=> Start and stop headless GRIP using NetworkTables

ui/src/main/java/edu/wpi/grip/ui/pipeline/SocketHandleView.java, ui/src/test/java/edu/wpi/grip/ui/pipeline/OutputSocketControllerTest.java
This should make it a little easier to figure stuff out by trial-and-error.  Basically, we used to check to make sure you didn't connect to sockets that weren't compatible (for example, they're different types, or one of them was already connected to something), but there was very little visual feedback to show what connections would be possible.
To do this, I replaced the `Optional<Socket>` that stores the socket being dragged with an `ObjectProperty<Socket>`.  This works nicely with JavaFX's event system and lets us have all sockets react when one of them is dragged.  We could also use a `ObjectProperty<Optional<Socket<?>>>`, but that would make any practical usage really verbose and hard to read.
=> When dragging, visually disable sockets that can't be dragged onto

appveyor.yml
Reverts WPIRoboticsProjects/GRIP#452
This isn't really a 32 bit build like we originally expected.
=> Revert "Adds a 32 bit windows release"

build.gradle
Upon merging this will resolve #461 
For users without Git on their PATH, build versions will default to the current HEAD Commit Tag read manually. Alternatively, users may also specify the 'vers' property (via `./gradlew task -Pvers=myversion`) if they want to tag the build with a specified version.
For users with Git on their PATH, the behavior of grabbing the current Tag remains unchanged.
=> Enable non-git builds

ui/src/main/java/edu/wpi/grip/ui/components/ExceptionWitnessResponderButton.java, ui/src/test/java/edu/wpi/grip/ui/components/ExceptionWitnessResponderButtonTest.java
The button was responding to events before being added to the scene thus
causing a null pointer exception.
Closes #539
=> Fixes Null Pointer from ExceptionWitnessResponderButton

ui/src/main/java/edu/wpi/grip/ui/DeployController.java, ui/src/main/java/edu/wpi/grip/ui/components/LogTextArea.java, ui/src/main/resources/edu/wpi/grip/ui/Deploy.fxml, ui/src/test/java/edu/wpi/grip/ui/components/LogTextAreaTest.java
The JavaFX thread would hang when the string being displayed
in the deploy UI became too long.
This ensures that if the string becomes too long it will
stop displaying more data.
=> Fixes DeployUI Freezing app if too much text is displayed

ui/src/main/resources/edu/wpi/grip/ui/pipeline/Pipeline.fxml
Without this, the sources window shrunk when enough processing steps were
added, making it at first hard to read and then impossible to use.
=> Pipeline: Use preferred size for min and max for sources window.

.travis.yml
=> Makes Travis fail fast if an os fails

build.gradle
IntelliJ has trouble discovering maven repositories nested within other types of dependency blocks in Gradle build scripts. This is fixed by moving them outside of the 'flatDir' block.
=> Improve IntelliJ indexing of additional Maven repositories

core/src/main/java/edu/wpi/grip/core/operations/CVOperations.java
Before:
After: 
Note that the blue rectangles are added to draw attention to the correct location and were not present during the running of GRIP. Also the operation worked correctly and the hint text was the only thing that was wrong.
=> Fixes issue with CV_Resize operation have fx socket hint twice

ui/src/main/resources/edu/wpi/grip/ui/MainWindow.fxml
Mac keyboard shortcuts used control before.  Now they use command.  Windows still uses control.
Tested on OS X 10.11.5 and Window 10.
=> Mac keyboard shortcuts now use command

.travis-scripts/install.sh, .travis.yml, core/src/test/java/edu/wpi/grip/core/util/service/AutoRestartingServiceTest.java
Java 8 is already installed in the newest image.
https://github.com/travis-ci/docs-travis-ci-com/issues/593
=> Update Travis OSX build to use newest image

core/src/test/java/edu/wpi/grip/core/ManualPipelineRunner.java, core/src/test/java/edu/wpi/grip/core/serialization/ProjectTest.java, core/src/test/java/edu/wpi/grip/util/GripCoreTestModule.java
It was a threading issue caused by `Project.open` immediately starting the pipeline asynchronously and not overriding the pipeline runner with the mock version.
=> Fix project serialization tests

core/src/main/java/edu/wpi/grip/core/operations/CVOperations.java
CV Threshold, CV AdaptiveThreshold, and CV GaussianBlur all have enums that caused errors when used. This creates new intermediary enums with fewer options to prevent errors in GRIP and make it much easier for users. CV Threshold with with THRESH_MASK caused GRIP to completely crash when used with video, so this change will also fix that.
=> Added enums with fewer options

core/src/main/java/edu/wpi/grip/core/settings/ProjectSettings.java
closes #536 
Changes the default roboRIO mDNS address to match capitalization as discussed in #536.
=> Update default roboRIO mDNS address

core/src/main/java/edu/wpi/grip/core/events/ConnectionAddedEvent.java, core/src/main/java/edu/wpi/grip/core/events/ConnectionRemovedEvent.java, core/src/main/java/edu/wpi/grip/core/events/DirtiesSaveEvent.java, core/src/main/java/edu/wpi/grip/core/events/SocketChangedEvent.java, core/src/main/java/edu/wpi/grip/core/events/SocketPreviewChangedEvent.java, core/src/main/java/edu/wpi/grip/core/events/SourceAddedEvent.java, core/src/main/java/edu/wpi/grip/core/events/SourceRemovedEvent.java, core/src/main/java/edu/wpi/grip/core/events/StepAddedEvent.java, core/src/main/java/edu/wpi/grip/core/events/StepMovedEvent.java, core/src/main/java/edu/wpi/grip/core/events/StepRemovedEvent.java, core/src/main/java/edu/wpi/grip/core/serialization/Project.java, ui/src/main/java/edu/wpi/grip/ui/Main.java, ui/src/main/java/edu/wpi/grip/ui/MainWindowController.java
closes #359 
#359  & adds "Edited" to the title bar when the project is dirty.
=> Adds save dirty checking event

ui/src/main/java/edu/wpi/grip/ui/preview/BlobsSocketPreviewView.java, ui/src/main/java/edu/wpi/grip/ui/preview/LinesSocketPreviewView.java
closes #679 
Fixes the bug in #679
=> Fix massive memory leak in previews (#679)

core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java
=> Fix webcam sources failing to stop when opening saved projects

ui/src/main/java/edu/wpi/grip/ui/MainWindowController.java
Fixes a deadlock when loading a project while an output image is being rendered
=> Solves deadlocking when opening a saved project

core/src/main/java/edu/wpi/grip/core/sockets/SocketImpl.java
This deadlock is caused by `SocketImpl.setValueOptional` being a synchronized method and posting a SocketChangedEvent that the UI thread tries to handle by locking on the socket when getting it's value.
=> Fix a potential deadlock on opening a project

build.gradle, core/src/main/java/edu/wpi/grip/core/CoreCommandLineHelper.java, core/src/main/java/edu/wpi/grip/core/Main.java, core/src/main/java/edu/wpi/grip/core/http/GripServer.java, core/src/test/java/edu/wpi/grip/core/CoreCommandLineHelperTest.java, core/src/test/java/edu/wpi/grip/core/CoreSanityTest.java, ui/src/main/java/edu/wpi/grip/ui/Main.java, ui/src/main/java/edu/wpi/grip/ui/UICommandLineHelper.java
Set the save file with `-f <path>` or `--file <path>`  
Set the HTTP server port with `-p <port>` or `--port <port>`  
Print the version with `-v` or `--version`  
Print help text with `-h` or `--help`  
Set headless mode with `--headless` (UI only)
Can pass command line args through gradle with `-Pargs="<args>"`
Note: this breaks backwards compatibility with loading files from the command line.
=> Add better support for command line arguments

core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java
Use `stopAsync()` and a thread sleep on OS X instead of `stopAndAwait()` due to a bug in the OpenCV camera capture class.
This closes #712
=> Fix removing webcams in OSX hanging

ui/src/main/java/edu/wpi/grip/ui/preview/RectangleSocketPreviewView.java
Now they don't freeze or show the original image when there's no rectangles
=> Fix rectangle previews

.travis.yml, ui/src/test/java/edu/wpi/grip/ui/codegeneration/AbstractGenerationTesting.java
This should be reverted once the package works again.
See #761
=> opencv-python package is broken; disable python codegen tests

ui/src/test/java/edu/wpi/grip/ui/pipeline/PipelineUITest.java
Only because we're so close to a release and this is causing CI tests to fail.
Temporary fix for #762
=> Disable broken testMinimizeButton test

build.gradle, git.gradle
This should fix all accounts where Git is not on the path. For cases where Git is not present, we return the commit as `<no commit>` and the Git tag/version as `v0.0.0`
=> Use Grgit instead of command-line Git invocation

core/src/main/java/edu/wpi/grip/core/Pipeline.java, core/src/test/java/edu/wpi/grip/core/PipelineTest.java, ui/src/main/java/edu/wpi/grip/ui/analysis/AnalysisController.java
Instead of throwing an exception. Threading stuff kills it.
Fixes #781
=> Pipeline.indexOf(Step) returns -1 if not present

core/src/main/java/edu/wpi/grip/core/Connection.java, core/src/main/java/edu/wpi/grip/core/GripCoreModule.java, core/src/main/java/edu/wpi/grip/core/Source.java, core/src/main/java/edu/wpi/grip/core/Step.java, core/src/main/java/edu/wpi/grip/core/events/AppSettingsChangedEvent.java, core/src/main/java/edu/wpi/grip/core/events/BenchmarkEvent.java, core/src/main/java/edu/wpi/grip/core/events/CodeGenerationSettingsChangedEvent.java, core/src/main/java/edu/wpi/grip/core/events/ConnectionAddedEvent.java, core/src/main/java/edu/wpi/grip/core/events/ConnectionRemovedEvent.java, core/src/main/java/edu/wpi/grip/core/events/DirtiesSaveEvent.java, core/src/main/java/edu/wpi/grip/core/events/EventLogger.java, core/src/main/java/edu/wpi/grip/core/events/LoggableEvent.java, core/src/main/java/edu/wpi/grip/core/events/ProjectSettingsChangedEvent.java, core/src/main/java/edu/wpi/grip/core/events/SourceAddedEvent.java, core/src/main/java/edu/wpi/grip/core/events/SourceRemovedEvent.java, core/src/main/java/edu/wpi/grip/core/events/StepAddedEvent.java, core/src/main/java/edu/wpi/grip/core/events/StepRemovedEvent.java, core/src/main/java/edu/wpi/grip/core/events/UnexpectedThrowableEvent.java, core/src/main/java/edu/wpi/grip/core/events/WarningEvent.java, core/src/main/java/edu/wpi/grip/core/sockets/Socket.java, ui/src/main/java/edu/wpi/grip/ui/Main.java, ui/src/main/java/edu/wpi/grip/ui/codegeneration/Exporter.java
The current logs are about 1100 lines of debugging stuff from guava and about zero lines of stuff from GRIP. This PR reverses that situation.
=> Improve logging

core/src/main/java/edu/wpi/grip/core/serialization/Project.java, ui/src/main/java/edu/wpi/grip/ui/MainWindowController.java
- Changes default save directory from the GRIP location to ~/GRIP/
- Shows warnings if the project couldn't be saved instead of crashing
Closes #800
=> Improve UX for saving files

ui/preloader/src/main/java/edu/wpi/grip/preloader/GripPreloader.java, ui/preloader/src/main/java/edu/wpi/grip/preloader/HexagonGrid.java, ui/preloader/src/main/resources/edu/wpi/grip/preloader/Preloader.css, ui/preloader/src/main/resources/edu/wpi/grip/preloader/Preloader.fxml
Remove the progress bar from the preloader as well
=> Make the preloader have a fancy background

ui/src/main/resources/edu/wpi/grip/ui/codegeneration/python/operations/CV_Sobel.vm
Fixed Issue #893 so that cv2.Sobel doesn't ignore kernel size and use default of 3.
=> Fixed Issue #893

.travis-scripts/osx-opencv-install.sh, .travis.yml
The mac builds hang on installing GCC or make. Disabling this makes the builds work, though the code generation tests will no longer run.
=> Disable code generation tests on Travis

.travis.yml, appveyor.yml, azure-pipelines.yml, build.gradle.kts
The logic in the task is based on the codecov Gradle example: https://github.com/codecov/example-gradle
=> Fix aggregate JaCoCo task and add codecov integration to Azure

ui/src/main/resources/edu/wpi/grip/ui/codegeneration/python/operations/Find_Lines.vm
=> Make generated find_lines python script include first line when run

README.md
JavaFX requires GTK2, and some newer Linux distributions may not include it
=> Add note in readme about GTK2 requirement

core/src/main/java/edu/wpi/grip/core/serialization/SourceConverter.java
Fixes a problem with video file sources loaded from a save file not having play/pause and scrubber controls
Closes #913
=> Initialize sources loaded from save file before firing event

ui/src/main/resources/edu/wpi/grip/ui/codegeneration/java/operations/Filter_Lines.vm
Original VM template was reassigning the filtered list to the outputs variable
which would have no effect on the contents of the passed-in argument.  Working
pipelines in the GRIP GUI would show zero filtered lines when the generated class
was used.
Altered the template to manipulate the passed-in list object instead, using
`clear()` and `addAll()`.
Note: there doesn't appear to be unit tests for the generated classes, and I
don't have time to write them.  I tested the fix using test cases in our
own FRC project that use the generated class.
=> Fixes #920 java codegen for filter lines

ui/src/main/java/edu/wpi/grip/ui/pipeline/input/RangeInputSocketController.java
A slider from 0-1 will show values to 2 decimal places ("0.01 - 0.07") instead of "1 - 1"
Fixes #927
=> Show decimals on range sliders with low bounds

annotation/src/main/java/edu/wpi/grip/annotation/operation/Description.java, build.gradle.kts, core/src/main/java/edu/wpi/grip/core/Source.java, core/src/main/java/edu/wpi/grip/core/http/PedanticHandler.java, core/src/main/java/edu/wpi/grip/core/serialization/Project.java
Make `check` depend on `javadoc` task to enforce proper Javadocs. This means we won't get surprised by invalid Javadoc when merging PRs into master (and deleting all the published docs on the website in the process)
=> Cleanup javadoc, force UTF-8 encoding in Javadoc tasks

ui/src/main/java/edu/wpi/grip/ui/preview/BlobsSocketPreviewView.java, ui/src/main/java/edu/wpi/grip/ui/preview/ContoursSocketPreviewView.java, ui/src/main/java/edu/wpi/grip/ui/preview/ImageBasedPreviewView.java, ui/src/main/java/edu/wpi/grip/ui/preview/ImageSocketPreviewView.java, ui/src/main/java/edu/wpi/grip/ui/preview/LinesSocketPreviewView.java, ui/src/main/java/edu/wpi/grip/ui/preview/PreviewsController.java, ui/src/main/java/edu/wpi/grip/ui/preview/RectangleSocketPreviewView.java, ui/src/main/java/edu/wpi/grip/ui/preview/ResizableImageView.java, ui/src/main/java/edu/wpi/grip/ui/preview/SocketPreviewView.java, ui/src/main/java/edu/wpi/grip/ui/preview/TitledPane.java, ui/src/main/java/edu/wpi/grip/ui/util/ImageConverter.java, ui/src/main/resources/edu/wpi/grip/ui/preview/Previews.fxml
No more previews clipping below the bottom that forced users to scroll up and down to see information displayed below the image (eg contour count)
Reimplement TitledPane and ImageView to get proper behavior. JavaFX `TitledPane` leaves a gap around the image when it's shrunk, and `ImageView`  is atrocious at resizing to fit its parent.
Remove the overloads in `ImageConverter` that take desired height, since the UI is now responsible for doing the resize calculations.
This is a better implementation of #711 and fix for #710
**Full size previews**
**Partially shrunk**
**Minimum size previews**
=> Make previews always fit vertically in the preview area

ui/src/main/java/edu/wpi/grip/ui/codegeneration/TemplateMethods.java, ui/src/main/java/edu/wpi/grip/ui/codegeneration/data/TInput.java, ui/src/main/java/edu/wpi/grip/ui/codegeneration/data/TPipeline.java
Code generation tests obviously need work, but this is the fix for now
=> Fix code generation using MatWrapper instead of Mat

azure-pipelines.yml, ui/ui.gradle.kts
Switch to Linux for running the UI tests
Install OpenJFX and openjdk through `apt`
=> Fix UI tests on Azure

azure-pipelines.yml, ui/ui.gradle.kts
=> Update jpackage to release 64

azure-pipelines.yml, buildSrc/src/main/kotlin/JpackageExec.kt
This should mean we no longer need to update the version every time oracle removes one.
=> Fix java 14 url to point to always existing version

ui/src/main/java/edu/wpi/grip/ui/Main.java, ui/src/main/java/edu/wpi/grip/ui/MainWindowController.java, ui/src/main/java/edu/wpi/grip/ui/ProjectSettingsEditor.java, ui/src/main/java/edu/wpi/grip/ui/analysis/AnalysisController.java, ui/src/main/java/edu/wpi/grip/ui/pipeline/AddSourceButton.java, ui/src/main/java/edu/wpi/grip/ui/util/DPIUtility.java, ui/src/main/resources/edu/wpi/grip/ui/AboutDialog.fxml, ui/src/main/resources/edu/wpi/grip/ui/GRIP.css, ui/src/main/resources/edu/wpi/grip/ui/MainWindow.fxml, ui/src/main/resources/edu/wpi/grip/ui/OperationList.fxml, ui/src/main/resources/edu/wpi/grip/ui/analysis/Analysis.fxml, ui/src/main/resources/edu/wpi/grip/ui/base.css, ui/src/main/resources/edu/wpi/grip/ui/material.css, ui/src/main/resources/edu/wpi/grip/ui/pipeline/OutputSocket.fxml, ui/src/main/resources/edu/wpi/grip/ui/pipeline/Pipeline.fxml, ui/src/main/resources/edu/wpi/grip/ui/pipeline/Step.fxml
Closes #664 
Makes dialogs appear centered on the main window, instead of centered on the primary screen (which was a problem on multi-monitor setups)
**Empty window**
**Pipeline**
**Step detail**
**Palette**
**Analysis dialog**
**Deploy dialog**
For reference only, since deploy is going to be removed
**Exception alert**
=> Use material design theme
