WPIRoboticsProjects/GRIP

src/main/java/edu/wpi/grip/core/Operation.java
src/main/java/edu/wpi/grip/core/Step.java
src/main/java/edu/wpi/grip/core/operations/PythonScriptOperation.java
src/main/java/edu/wpi/grip/core/operations/opencv/AddOperation.java
src/test/java/edu/wpi/grip/core/AdditionOperation.java
src/test/java/edu/wpi/grip/core/PythonTest.java
src/test/java/edu/wpi/grip/core/StepTest.java
src/test/resources/edu/wpi/grip/scripts/addition-with-name-and-description.py

We need some way for operations to specify user-presentable strings of
information for the GUI.

Add getName() and getDescription() to the Operation interface

---

src/main/java/edu/wpi/grip/core/Connection.java
src/main/java/edu/wpi/grip/core/InputSocket.java
src/main/java/edu/wpi/grip/core/Operation.java
src/main/java/edu/wpi/grip/core/OutputSocket.java
src/main/java/edu/wpi/grip/core/Socket.java
src/main/java/edu/wpi/grip/core/Step.java
src/main/java/edu/wpi/grip/core/events/SocketPreviewChangedEvent.java
src/main/java/edu/wpi/grip/core/events/SocketPublishedEvent.java
src/main/java/edu/wpi/grip/core/operations/PythonScriptOperation.java
src/main/java/edu/wpi/grip/core/operations/opencv/AddOperation.java
src/main/java/edu/wpi/grip/core/sinks/DummySink.java
src/main/java/edu/wpi/grip/core/sources/ImageFileSource.java
src/main/java/edu/wpi/grip/ui/InputSocketView.java
src/main/java/edu/wpi/grip/ui/OutputSocketView.java
src/main/java/edu/wpi/grip/ui/SocketHandleView.java
src/main/java/edu/wpi/grip/ui/StepView.java
src/test/java/edu/wpi/grip/core/AdditionOperation.java
src/test/java/edu/wpi/grip/core/ConnectionTest.java
src/test/java/edu/wpi/grip/core/OperationTest.java
src/test/java/edu/wpi/grip/core/PipelineTest.java
src/test/java/edu/wpi/grip/core/SinkTest.java
src/test/java/edu/wpi/grip/core/SocketTest.java
src/test/java/edu/wpi/grip/core/operations/opencv/AddOperationTest.java
src/test/java/edu/wpi/grip/core/serialization/SerializationTest.java
src/test/java/edu/wpi/grip/core/sources/ImageFileSourceTest.java

Since input sockets and output sockets have different functionality and
need to be distinguished they have been seperated into different
classes.

Adds InputSocket & OutputSocket

---

src/main/java/edu/wpi/grip/ui/pipeline/InputSocketView.java
src/main/java/edu/wpi/grip/ui/preview/ImageSocketPreviewView.java

Checkbox controls are added, and the preview pane can now show grayscale
images like the one that canny outputs

Make canny work with the GUI

---

src/main/java/edu/wpi/grip/ui/controllers/MainWindowController.java

Helps resolve the obscure errors without context we were getting from the EventBus

Adds StackTrace Printing for EventBus

---

.travis.yml
build.gradle
src/main/java/edu/wpi/grip/ui/OperationView.java
src/main/java/edu/wpi/grip/ui/pipeline/ConnectionView.java
src/main/java/edu/wpi/grip/ui/pipeline/SocketHandleView.java
src/main/java/edu/wpi/grip/ui/pipeline/StepView.java
src/main/java/edu/wpi/grip/ui/util/StyleClassNameUtility.java
src/test/java/edu/wpi/grip/core/SubtractionOperation.java
src/test/java/edu/wpi/grip/ui/controllers/MainWindowControllerTest.java
src/test/java/edu/wpi/grip/ui/pipeline/PipelineViewTest.java

JavaFX tests should now run as part of the build.
Tests should work headless on Travis.

Adds JavaFX Testing to Build

---

buildSrc/src/main/java/edu/wpi/gripgenerator/FileParser.java
buildSrc/src/main/java/edu/wpi/gripgenerator/OpenCVEnumVisitor.java
buildSrc/src/main/java/edu/wpi/gripgenerator/defaults/DefaultValueCollector.java
buildSrc/src/main/java/edu/wpi/gripgenerator/settings/DefinedMethod.java
buildSrc/src/main/java/edu/wpi/gripgenerator/settings/DefinedMethodCollection.java
buildSrc/src/main/java/edu/wpi/gripgenerator/settings/DefinedParamType.java
buildSrc/src/main/java/edu/wpi/gripgenerator/templates/Enumeration.java
buildSrc/src/main/java/edu/wpi/gripgenerator/templates/Operation.java
buildSrc/src/main/java/edu/wpi/gripgenerator/templates/SocketHintDeclaration.java
buildSrc/src/main/java/edu/wpi/gripgenerator/templates/SocketHintDeclarationCollection.java
buildSrc/src/test/java/templates/SocketHintDeclarationTest.java
src/main/java/edu/wpi/grip/core/operations/opencv/enumeration/FlipCode.java

Generator can now generate enumerations for any opencv source files

Refactors the enumeration generation code

---

src/main/java/edu/wpi/grip/core/events/SocketConnectedChangedEvent.java

Documentation Fix SocketConnectedChangedEvent

---

src/main/java/edu/wpi/grip/core/Operation.java
src/main/java/edu/wpi/grip/core/events/OperationAddedEvent.java
src/main/java/edu/wpi/grip/ui/PaletteView.java
src/main/java/edu/wpi/grip/ui/controllers/MainWindowController.java
src/test/java/edu/wpi/grip/ui/controllers/MainWindowControllerTest.java

This will make it easier to have things like serialization and
dynamically loading scripts

Refactor the operation list to use events instead of JavaFX properties

---

src/main/java/edu/wpi/grip/core/sources/WebcamSource.java

Webcameras can now be removed when the delete button is pressed.
Closes #80

Allows Webcam Sources to be removed

---

buildSrc/src/main/java/edu/wpi/gripgenerator/templates/OperationList.java
src/main/java/edu/wpi/grip/ui/controllers/MainWindowController.java

The application now keeps track of new operations using events.  This
change will update the generator code to make these events instead of a
static list.

Auto-generate code to post generated operations

---

src/main/java/edu/wpi/grip/core/operations/composite/HSVThresholdOperation.java
src/main/java/edu/wpi/grip/ui/controllers/MainWindowController.java

Allows users to perform the HSV Threhold operation on an image
Related #86

Adds HSV Threshold Operation

---

README.md

Reverts WPIRoboticsProjects/GRIP#91

Revert 357f1ce368b1b086013724b016d40c806bc0673e

---

src/main/java/edu/wpi/grip/core/operations/composite/HSLThresholdOperation.java
src/main/java/edu/wpi/grip/core/operations/composite/HSVThresholdOperation.java
src/main/java/edu/wpi/grip/ui/controllers/MainWindowController.java

Allows users to perform the HLS Threhold operation on an image
Related #86

Adds HLSThreshold Operation

---

src/main/java/edu/wpi/grip/core/operations/composite/FindLinesOperation.java
src/main/java/edu/wpi/grip/core/operations/composite/LinesReport.java
src/main/java/edu/wpi/grip/ui/pipeline/ConnectionView.java
src/main/java/edu/wpi/grip/ui/pipeline/input/RangeInputSocketView.java
src/main/java/edu/wpi/grip/ui/preview/TextAreaSocketPreviewView.java

Fixes several problems with scoping across the program.
Closes #92

Use explicit scoping instead of the default package private level

---

src/main/java/edu/wpi/grip/core/Connection.java
src/main/java/edu/wpi/grip/core/Pipeline.java
src/main/java/edu/wpi/grip/core/Step.java
src/main/java/edu/wpi/grip/ui/pipeline/SocketHandleView.java
src/test/java/edu/wpi/grip/core/PipelineTest.java

Add validation for creating connections

---

src/main/java/edu/wpi/grip/ui/preview/BlobsSocketPreviewView.java
src/main/java/edu/wpi/grip/ui/preview/LinesSocketPreviewView.java
src/main/java/edu/wpi/grip/ui/preview/PointSizeSocketPreviewView.java
src/main/java/edu/wpi/grip/ui/preview/SocketPreviewViewFactory.java

Points and sizes can be previewed, and the background image in blob/line
previews can be disabled

Add more preview enhancements

---

.travis.yml
appveyor.yml

Appveyor needed a auth_token
TravisCI needed the path to be specified differently

Fixes Automated CI Releases Not working

---

src/main/java/edu/wpi/grip/ui/pipeline/input/ListSpinnerInputSocketView.java
src/main/java/edu/wpi/grip/ui/pipeline/input/NumberSpinnerInputSocketView.java

Would close https://trello.com/c/ItVmvdMv (trello card 74) and issue #129

Text field of spinner now updates socket value when focus is lost.

---

src/main/java/edu/wpi/grip/ui/pipeline/input/RangeInputSocketView.java
src/main/java/edu/wpi/grip/ui/pipeline/input/SliderInputSocketView.java

Add labels next to sliders to show exact values

---

src/main/java/edu/wpi/grip/ui/ExceptionAlert.java
src/main/java/edu/wpi/grip/ui/Main.java

This should kill the application completely if the application has a problem

Tries using System.exit(1) to kill the application

---

src/main/java/edu/wpi/grip/core/events/ExceptionClearedEvent.java
src/main/java/edu/wpi/grip/core/events/ExceptionEvent.java
src/main/java/edu/wpi/grip/core/util/ExceptionWitness.java
src/test/java/edu/wpi/grip/core/util/ErrorWitnessTest.java

Adds Exception Handling Events with an Exception Witness

---

src/main/java/edu/wpi/grip/ui/pipeline/input/NumberSpinnerInputSocketView.java
src/main/java/edu/wpi/grip/ui/pipeline/input/RangeInputSocketView.java
src/main/java/edu/wpi/grip/ui/pipeline/input/SliderInputSocketView.java

Fixes Domain Usage in InputSocketViews

---

build.gradle

Fix for issue with OS detector classifier for windows 32 bit

This fixes an issue with the OS detector classifier for 32 bit windows.

---

core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java

Fix Divide by Zero Error in CameraSource

---

ui/src/main/java/edu/wpi/grip/ui/ExceptionAlert.java

Does what it says in the label.

Adds Version Number to ExceptionAlert's system info

---

.gitignore
core/src/main/java/edu/wpi/grip/core/Main.java
ui/src/main/java/edu/wpi/grip/ui/Main.java

Fixed file handling and location issues.

Logging feature

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Updates to Gradle 2.10

---

ui/src/main/java/edu/wpi/grip/ui/preview/PreviewsController.java

Fixes NoSuchElement when previewing a Source then a Step

---

ui/src/main/java/edu/wpi/grip/ui/preview/BlobsSocketPreviewView.java

Fixes BlobsSocketPreview Showing background image if 0 blobs

---

ui/src/main/java/edu/wpi/grip/ui/pipeline/AddSourceView.java

Select image files only

---

core/src/main/java/edu/wpi/grip/core/sources/ImageFileSource.java
core/src/test/java/edu/wpi/grip/core/sources/ImageFileSourceTest.java

Fix file source not deserializing correctly in UI

---

ui/src/main/java/edu/wpi/grip/ui/pipeline/input/InputSocketController.java

Fixes it so enum "types" are not displayed in step gui element.This would close issue #112

Enum format fix

---

ui/src/main/java/edu/wpi/grip/ui/pipeline/input/RangeInputSocketController.java

Set ranged slider values properly

---

core/src/main/java/edu/wpi/grip/core/operations/Operations.java
core/src/main/java/edu/wpi/grip/core/operations/composite/FilterLinesOperation.java
core/src/main/java/edu/wpi/grip/core/operations/composite/FindLinesOperation.java
core/src/main/java/edu/wpi/grip/core/operations/composite/LinesReport.java

This adds a bunch of @NTValue properties to LinesReport that can be published to NetworkTables, including the start and end points, length, and angle of each line (angle was also added to `FilterLinesOperation`)
Closes #289

Make LinesReport publishable

---

ui/src/main/java/edu/wpi/grip/ui/util/deployment/DeployedInstanceManager.java

The deployer now coppies and renames the core grip jar to
`grip-core.jar` and SCPs that file over every time instead of
coping the original source code.
Closes #305

Makes deployer deploy to grip-core.jar

---

ui/src/main/java/edu/wpi/grip/ui/util/deployment/DeployedInstanceManager.java

Thanks to PMD for catching this one

Perserve exception if copy fails

---

core/src/main/java/edu/wpi/grip/core/GRIPCoreModule.java
core/src/main/java/edu/wpi/grip/core/Main.java
core/src/main/java/edu/wpi/grip/core/events/UnexpectedThrowableEvent.java
core/src/test/java/edu/wpi/grip/core/sources/CameraSourceTest.java
ui/src/main/java/edu/wpi/grip/ui/Main.java

Fix windows not shutting down when application stopped

---

core/src/main/java/edu/wpi/grip/core/operations/networktables/NTManager.java
core/src/main/java/edu/wpi/grip/core/settings/ProjectSettings.java
ui/src/main/java/edu/wpi/grip/ui/DeployerController.java
ui/src/main/java/edu/wpi/grip/ui/deployment/DeploymentOptionsController.java
ui/src/main/java/edu/wpi/grip/ui/deployment/FRCAdvancedDeploymentOptionsController.java
ui/src/main/java/edu/wpi/grip/ui/deployment/FRCDeploymentOptionsController.java
ui/src/main/java/edu/wpi/grip/ui/pipeline/input/NumberSpinnerInputSocketController.java
ui/src/main/java/edu/wpi/grip/ui/util/Spinners.java

- The deploy UI resizing when labels change size
- Adds a label to the play button in deploying
- Deploying now uses project defaults
- Ensure changing the team number will commit that value
Closes #301 #299 #282 #258

Fixes various Deployment UI Issues

---

core/src/main/java/edu/wpi/grip/core/operations/networktables/NTManager.java
core/src/main/java/edu/wpi/grip/core/settings/ProjectSettings.java
ui/src/main/java/edu/wpi/grip/ui/deployment/FRCAdvancedDeploymentOptionsController.java

This includes null checks and lots of typos
Closes #317

Fix some issues with ProjectSettings

---

core/src/main/java/edu/wpi/grip/core/settings/ProjectSettings.java

Combine address generator functions

---

ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java

Also connections flickering when moving.
Closes #321
Before:
After:

Fix connections not positioning correctly when loading project

---

core/src/main/java/edu/wpi/grip/core/Pipeline.java
core/src/main/java/edu/wpi/grip/core/operations/networktables/NTManager.java
core/src/main/java/edu/wpi/grip/core/operations/networktables/NTPublishOperation.java
core/src/main/java/edu/wpi/grip/core/settings/ProjectSettings.java
core/src/test/java/edu/wpi/grip/core/serialization/ProjectTest.java

NetworkTables now initializes itself when we try to publish something, and shuts down if there are no NetworkTables steps.
Closes #313

Remove network protocol setting

---

core/src/main/java/edu/wpi/grip/core/operations/Operations.java
core/src/main/java/edu/wpi/grip/core/operations/networktables/NTNumber.java
core/src/main/java/edu/wpi/grip/core/operations/networktables/NTPublishOperation.java
core/src/main/java/edu/wpi/grip/core/operations/networktables/NTValue.java
core/src/main/java/edu/wpi/grip/core/operations/networktables/NTVector2D.java

Closes #351
#351 suggests two features (read and write).  The one that this does not fix is also described in #363

Add publish operations for number, point, and size

---

ui/src/main/java/edu/wpi/grip/ui/preview/SocketPreviewView.java

Fix weird character rendering on Windows

---

build.gradle
core/src/main/java/edu/wpi/grip/core/GRIPCoreModule.java

GRIP Versions will now be pulled from git instead of manually entered

Release v1.1.0

---

ui/src/main/java/edu/wpi/grip/ui/DeployController.java

Disable host key verification for deploying

---

build.gradle

Fixed maintainer email address field to stop Lintian's complaints.

---

core/src/test/java/edu/wpi/grip/core/serialization/CompatibilityTest.java
core/src/test/java/edu/wpi/grip/util/Files.java
core/src/test/resources/edu/wpi/grip/projects/testALL.grip
testALL.grip

Issue316: make a test for ALL the steps to ensure backwards compatibility.

---

build.gradle

Updates to Guava 19

---

core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java
core/src/main/java/edu/wpi/grip/core/sources/IPCameraFrameGrabber.java

- The IPCameraFrameGrabber was stuck in an infinte loop
waiting for the rest of the image to arrive.
This was fixed by using a DataInputStream instead
- An unexpected end of the stream would cause a null
pointer exception. Now throws an EOFException. #390
Closes #390
Closes #427
Closes #404
Closes #387
Closes #436
Related bytedeco/javacv#322

Fixes IP Cameras Hanging

---

ui/src/main/java/edu/wpi/grip/ui/preview/ImageSocketPreviewView.java

Make image previews actually work

---

appveyor.yml

Adds a 32 bit windows release

---

ui/src/test/java/edu/wpi/grip/ui/MainWindowTest.java

Fix AppVeyor?

---

buildSrc/src/main/java/edu/wpi/gripgenerator/FileParser.java
buildSrc/src/main/java/edu/wpi/gripgenerator/templates/OperationList.java
buildSrc/src/main/java/edu/wpi/gripgenerator/templates/SocketHintDeclarationCollection.java
core/src/main/java/edu/wpi/grip/core/Connection.java
core/src/main/java/edu/wpi/grip/core/serialization/Project.java
core/src/main/java/edu/wpi/grip/core/serialization/SocketConverter.java
core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java
core/src/main/java/edu/wpi/grip/core/sources/MultiImageFileSource.java
core/src/main/java/edu/wpi/grip/core/util/SafeShutdown.java
ui/src/main/java/edu/wpi/grip/ui/DeployController.java
ui/src/main/java/edu/wpi/grip/ui/util/GRIPPlatform.java
ui/src/main/java/edu/wpi/grip/ui/util/StringInMemoryFile.java

- There were several performant issues.
- Now we use UTF-8 file encoding for all save writing/reading/uploading

Cleans up most of FindBugs Warnings

---

buildSrc/src/main/java/edu/wpi/gripgenerator/FileParser.java

Merge request to resolve issue #508

Support opencv transpose

---

core/src/main/java/edu/wpi/grip/core/operations/composite/FilterContoursOperation.java

Fixes #538. The default value and minimum value were switched.

Fixed Max Vertices defaulting to zero and displaying 1,000,000

---

core/src/main/java/edu/wpi/grip/core/GRIPCoreModule.java
core/src/main/java/edu/wpi/grip/core/Pipeline.java
core/src/main/java/edu/wpi/grip/core/operations/network/networktables/NTManager.java
core/src/main/java/edu/wpi/grip/core/settings/SettingsProvider.java
ui/src/main/java/edu/wpi/grip/ui/DeployController.java
ui/src/main/java/edu/wpi/grip/ui/MainWindowController.java

This makes it so that the pipeline doesn't have
to be injected into places that doesn't make any sense.

Makes SettingsProvider an interface

---

core/src/main/java/edu/wpi/grip/core/Source.java
core/src/main/java/edu/wpi/grip/core/Step.java
core/src/main/java/edu/wpi/grip/core/serialization/SocketConverter.java
core/src/test/java/edu/wpi/grip/core/PipelineTest.java
core/src/test/java/edu/wpi/grip/core/PythonTest.java
core/src/test/java/edu/wpi/grip/core/StepTest.java
core/src/test/java/edu/wpi/grip/core/serialization/ProjectTest.java
core/src/test/java/edu/wpi/grip/core/sources/ImageFileSourceTest.java
core/src/test/java/edu/wpi/grip/core/sources/MultiImageFileSourceTest.java
ui/src/main/java/edu/wpi/grip/ui/preview/PreviewsController.java
ui/src/test/java/edu/wpi/grip/ui/pipeline/input/InputSocketControllerFactoryTest.java

This is much cleaner code and is better encapsulated.

Changes Step getInput/OutputSockets() to return ImmutableList

---

core/src/main/java/edu/wpi/grip/core/OperationMetaData.java
core/src/main/java/edu/wpi/grip/core/operations/CVOperations.java
core/src/main/java/edu/wpi/grip/core/operations/Operations.java
core/src/main/java/edu/wpi/grip/core/operations/templated/FiveSourceOneDestinationOperation.java
core/src/main/java/edu/wpi/grip/core/operations/templated/FourSourceOneDestinationOperation.java
core/src/main/java/edu/wpi/grip/core/operations/templated/OneSourceOneDestinationOperation.java
core/src/main/java/edu/wpi/grip/core/operations/templated/SevenSourceOneDestinationOperation.java
core/src/main/java/edu/wpi/grip/core/operations/templated/SixSourceOneDestinationOperation.java
core/src/main/java/edu/wpi/grip/core/operations/templated/TemplateFactory.java
core/src/main/java/edu/wpi/grip/core/operations/templated/ThreeSourceOneDestinationOperation.java
core/src/main/java/edu/wpi/grip/core/operations/templated/TwoSourceOneDestinationOperation.java
core/src/test/java/edu/wpi/grip/core/operations/OperationsTest.java

Fix Templated Operations not running

---

core/src/main/java/edu/wpi/grip/core/operations/CVOperations.java

- CV erode
- CV dilate
- CV bitwise_not

Fix Various Operations being wrong

---

.travis.yml
appveyor.yml
build.gradle

Will make it clearer if a test is hanging

Makes tests report while running on CI systems

---

build.gradle

This updates the versions of xstream, auto-value, guice, guice-assistedinject, and sshj.

Update xstream, auto-value, guice, guice-assistedinject, sshj

---

ui/src/main/java/edu/wpi/grip/ui/ExceptionAlert.java

Fix GitHub typo

---

build.gradle
checkstyle.xml
core/src/test/java/edu/wpi/grip/core/PipelineRunnerTest.java
core/src/test/java/edu/wpi/grip/core/operations/opencv/AddOperationTest.java

Block (non-Javadoc) and System.out.println using checkstyle

---

ui/src/main/java/edu/wpi/grip/ui/Main.java

Event bus should not be used for this anyway...

Missing operations hot fix

---

core/src/main/java/edu/wpi/grip/core/serialization/Project.java
ui/src/main/java/edu/wpi/grip/ui/Main.java

As discussed in the hangouts...

Fix bug introduced in #647

---

core/src/main/java/edu/wpi/grip/core/sources/ImageFileSource.java
core/src/main/java/edu/wpi/grip/core/sources/MultiImageFileSource.java
core/src/test/java/edu/wpi/grip/util/ImageWithData.java
ui/src/main/java/edu/wpi/grip/ui/DeployController.java
ui/src/test/java/edu/wpi/grip/ui/util/ImageConverterTest.java

Cleanup of deprecated method usages

---

.travis.yml
appveyor.yml
build.gradle

- Continuous integration services now run the check task
- Adds the [taskTree plugin](https://plugins.gradle.org/plugin/com.dorongold.task-tree) to view tasks that will be executed (utility plugin)
Check runs these tasks now (this is the tree from core):
```
:core:check
+--- :core:checkstyleGenerated
+--- :core:checkstyleMain
+--- :core:checkstyleTest
+--- :core:findbugsMain
|    \--- :core:classes
|         +--- :core:compileJava
|         |    \--- :core:generateCodeFromSource
|         \--- :core:processResources
+--- :core:findbugsTest
|    +--- :core:classes
|    |    +--- :core:compileJava
|    |    |    \--- :core:generateCodeFromSource
|    |    \--- :core:processResources
|    \--- :core:testClasses
|         +--- :core:compileTestJava
|         |    \--- :core:classes
| …
```

Update ./gradlew check to run on test files

---

ui/src/main/java/edu/wpi/grip/ui/Main.java

Solve ordering issue when opening a file via command line

---

ui/src/main/java/edu/wpi/grip/ui/codegeneration/Exporter.java

Fix code generation with Windows native app

---

core/src/main/java/edu/wpi/grip/core/sources/ImageFileSource.java
core/src/main/java/edu/wpi/grip/core/sources/MultiImageFileSource.java

Don't parse image paths as URLs

---

ui/src/main/java/edu/wpi/grip/ui/pipeline/input/RangeInputSocketController.java

Fix range input deserialization

---

core/src/main/java/edu/wpi/grip/core/Pipeline.java

Make Pipeline.eventBus transient

---

ui/src/main/resources/edu/wpi/grip/ui/codegeneration/python/operations/Blur.vm
ui/src/main/resources/edu/wpi/grip/ui/codegeneration/python/operations/RGB_Threshold.vm
ui/src/test/java/edu/wpi/grip/ui/codegeneration/RGBThresholdTesting.java

Fix Blur and RGBThreshold for Python. Add RGBThreshold tests

---

build.gradle

Update NetworkTables to 3.1.2 and use the FRC releases repo

---

ui/src/main/resources/edu/wpi/grip/ui/codegeneration/cpp/Pipeline.h.vm
ui/src/main/resources/edu/wpi/grip/ui/codegeneration/cpp/Pipeline.vm
ui/src/main/resources/edu/wpi/grip/ui/codegeneration/cpp/macros.vm
ui/src/main/resources/edu/wpi/grip/ui/codegeneration/cpp/operations/Convex_Hulls.vm
ui/src/main/resources/edu/wpi/grip/ui/codegeneration/cpp/operations/Filter_Contours.vm
ui/src/main/resources/edu/wpi/grip/ui/codegeneration/cpp/operations/Filter_Lines.vm
ui/src/main/resources/edu/wpi/grip/ui/codegeneration/cpp/operations/Find_Contours.vm

Addresses issue #744, which I almost certainly caused :-(

Fix issue #744, related to failed code generation with contours

---

CONTRIBUTING.md

Update CONTRIBUTING.md with info about author tag

---

core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java
core/src/main/java/edu/wpi/grip/core/util/service/AutoRestartingService.java
core/src/main/java/edu/wpi/grip/core/util/service/CooldownRestartPolicy.java
core/src/main/java/edu/wpi/grip/core/util/service/ServiceRestartPolicy.java
core/src/test/java/edu/wpi/grip/core/util/service/AutoRestartingServiceTest.java
ui/src/test/java/edu/wpi/grip/ui/components/StartStoppableButtonTest.java

Limit camara connection retries to 50Hz

---

ui/src/main/java/edu/wpi/grip/ui/MainWindowController.java

An alert will show every time, even in the same session, for maximum annoyance

Discourage use of the deploy tool

---

core/src/main/java/edu/wpi/grip/core/serialization/CodeGenerationSettingsConverter.java
core/src/main/java/edu/wpi/grip/core/settings/CodeGenerationSettings.java
ui/src/main/java/edu/wpi/grip/ui/codegeneration/CodeGenerationOptionsController.java

Set codegen save dir to default if it's invalid

---

core/src/main/java/edu/wpi/grip/core/settings/CodeGenerationSettings.java

Set default codegen dir to ~/GRIP

---

ui/src/main/resources/edu/wpi/grip/ui/codegeneration/java/operations/Find_Blobs.vm

Fix generated Java blob detection

---

ui/src/main/java/edu/wpi/grip/ui/pipeline/OutputSocketController.java
ui/src/main/java/edu/wpi/grip/ui/preview/ContoursSocketPreviewView.java
ui/src/main/java/edu/wpi/grip/ui/preview/ImageBasedPreviewView.java
ui/src/main/java/edu/wpi/grip/ui/preview/ImageSocketPreviewView.java

Don't allow non-previewable values to be previewed

---

build.gradle

Use specific version of testfx

---

.travis.yml

Enable python code generation on OSX

---

README.md

Add link to example code in GRIP README

---

README.md

Update README to mention 2017 game

---

build.gradle

Update xstream version to 1.4.10 to fix security issue

---

ui/preloader/src/main/java/edu/wpi/grip/preloader/GripPreloader.java
ui/preloader/src/main/resources/edu/wpi/grip/preloader/Preloader.css

Change preloader to a light background

---

.azure-scripts/push-javadoc-to-gh-pages.sh

Was doing an improper check on environment variables

Fix Javadoc publishing from Azure

---

.azure-scripts/push-javadoc-to-gh-pages.sh
azure-pipelines.yml

Should fix Javadoc publishing this time

Manually set GH_TOKEN env var

---

build.gradle.kts

Force UTF-8 for all Javadoc tasks

---

azure-pipelines.yml

Add publish task to azure

---

azure-pipelines.yml
ui/ui.gradle.kts

Fix publishing by flattening directory first

---

azure-pipelines.yml

Also switches to AdoptOpenJDK for JDK version to have a common platform

Update to release Java 14 for jpackage
